name: ci

on:
  push:
    branches:
      - master
      # Not all of these branches might exist.
      - 2.4
      - 2.6
      - 2.8
      - 2.10
      - 2.12
      - 2.14
      - 2.16
    paths-ignore:
      - README.md

  # Run tests for any PRs.
  pull_request:
    branches:
      - master

    paths-ignore:
      - README.md

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    if: >
      (github.event_name == 'push' &&
       !contains(github.event.head_commit.message, 'skip ci') &&
       !contains(github.event.head_commit.message, 'ci skip') &&
       !contains(github.event.head_commit.message, 'skip github actions')) ||
      github.event_name == 'pull_request'
    strategy:
      # To avoid terminating all jobs when one job fails.
      fail-fast: false
      matrix:
        include:
          # ---------------------------------------------------------------------------------------
          # CentOS 7
          # ---------------------------------------------------------------------------------------
          - name: centos7-x86_64-gcc11
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_centos7_x86_64:v2022-10-13T18_10_48
            build_thirdparty_args: >-
              --devtoolset=11
              --expected-major-compiler-version=11

          # Clang 15
          - name: centos7-x86_64-clang15
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_centos7_x86_64:v2022-10-13T18_10_48
            build_thirdparty_args: >-
              --toolchain=llvm15
              --expected-major-compiler-version=15

          - name: centos7-x86_64-clang15-full-lto
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_centos7_x86_64:v2022-10-13T18_10_48
            build_thirdparty_args: >-
              --toolchain=llvm15
              --expected-major-compiler-version=15
              --lto=full

          # Clang 16
          - name: centos7-x86_64-clang16
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_centos7_x86_64:v2022-10-13T18_10_48
            build_thirdparty_args: >-
              --toolchain=llvm16
              --expected-major-compiler-version=16

          - name: centos7-x86_64-clang16-full-lto
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_centos7_x86_64:v2022-10-13T18_10_48
            build_thirdparty_args: >-
              --toolchain=llvm16
              --expected-major-compiler-version=16
              --lto=full

          # ---------------------------------------------------------------------------------------
          # Ubuntu 20.04
          # ---------------------------------------------------------------------------------------
          - name: ubuntu2004-x86_64-clang15
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_ubuntu2004_x86_64:v2022-10-13T18_10_48
            build_thirdparty_args: >-
              --toolchain=llvm15
              --expected-major-compiler-version=15

          # ---------------------------------------------------------------------------------------
          # Ubuntu 22.04
          # ---------------------------------------------------------------------------------------

          - name: ubuntu2204-x86_64-gcc11
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_ubuntu2204_x86_64:v2022-10-13T18_10_50
            build_thirdparty_args: >-
              --compiler-prefix=/usr
              --compiler-family=gcc
              --compiler-suffix=-11
              --expected-major-compiler-version=11

          - name: ubuntu2204-x86_64-clang15
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_ubuntu2204_x86_64:v2022-10-13T18_10_50
            build_thirdparty_args: >-
              --toolchain=llvm15
              --expected-major-compiler-version=15

          # ---------------------------------------------------------------------------------------
          # AlmaLinux 8
          # ---------------------------------------------------------------------------------------
          - name: almalinux8-x86_64-gcc11
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_almalinux8_x86_64:v2022-10-13T18_10_49
            build_thirdparty_args: >-
              --devtoolset=11
              --expected-major-compiler-version=11

          # Clang/LLVM 15
          - name: almalinux8-x86_64-clang15
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_almalinux8_x86_64:v2022-10-13T18_10_49
            build_thirdparty_args: >-
              --toolchain=llvm15
              --expected-major-compiler-version=15

          - name: almalinux8-x86_64-clang15-linuxbrew
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_almalinux8_x86_64:v2022-10-13T18_10_49
            build_thirdparty_args: >-
              --toolchain=llvm15_linuxbrew
              --expected-major-compiler-version=15

          - name: almalinux8-x86_64-clang15-linuxbrew-full-lto
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_almalinux8_x86_64:v2022-10-13T18_10_49
            build_thirdparty_args: >-
              --toolchain=llvm15_linuxbrew
              --expected-major-compiler-version=15
              --lto=full

          # Clang/LLVM 16
          - name: almalinux8-x86_64-clang16
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_almalinux8_x86_64:v2022-10-13T18_10_49
            build_thirdparty_args: >-
              --toolchain=llvm16
              --expected-major-compiler-version=16

          - name: almalinux8-x86_64-clang16-linuxbrew
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_almalinux8_x86_64:v2022-10-13T18_10_49
            build_thirdparty_args: >-
              --toolchain=llvm16_linuxbrew
              --expected-major-compiler-version=16

          - name: almalinux8-x86_64-clang16-linuxbrew-full-lto
            os: ubuntu-20.04  # Ubuntu 20.04 is for the top-level VM only. We use Docker in it.
            docker_image: yugabyteci/yb_build_infra_almalinux8_x86_64:v2022-10-13T18_10_49
            build_thirdparty_args: >-
              --toolchain=llvm16_linuxbrew
              --expected-major-compiler-version=16
              --lto=full

          # ---------------------------------------------------------------------------------------
          # macOS
          # ---------------------------------------------------------------------------------------

          - name: macos-x86_64
            os: macos-11.7
            docker_image:
            build_thirdparty_args:

    steps:
      - name: Increase disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          # We need to fetch all history because we are cloning the checkout directory further
          # in test code.
          fetch-depth: 0

      - name: Build
        run: |
          if [[ $OSTYPE == darwin* ]]; then
            ./.github/workflows/macos_build.sh
          else
            ./.github/workflows/linux_build.sh
          fi
        env:
          YB_DOCKER_IMAGE: ${{ matrix.docker_image }}
          YB_THIRDPARTY_ARCHIVE_NAME_SUFFIX: ${{ matrix.name }}
          YB_BUILD_THIRDPARTY_ARGS: ${{ matrix.build_thirdparty_args }}
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH_TOKEN }}

      - uses: actions/upload-artifact@v2
        with:
          name: yugabyte-db-thirdparty-${{ matrix.name }}.tar.gz
          path: archive.tar.gz

      - uses: actions/upload-artifact@v2
        with:
          name: yugabyte-db-thirdparty-${{ matrix.name }}.tar.gz.sha256
          path: archive.tar.gz.sha256
